application: gds-session-demo
version: demo
runtime: php55
api_version: 1
threadsafe: yes

handlers:

# Favicon

- url: /favicon\.ico
  static_files: examples/favicon.ico
  upload: examples/favicon\.ico

# Default rule

- url: .*
  script: examples/index.php
  secure: always